package net.ai.webabackend.modal;



public enum SecteurActivite {
    SANTE_ET_BIEN_ETRE,
    EDUCATION,
    TECHNOLOGIE_DE_L_INFORMATION,
    INDUSTRIE_MANUFACTURIERE,
    SERVICES_PROFESSIONNELS,
    IMMOBILIER,
    COMMERCE_DE_DETAIL,
    HOTELLERIE_ET_RESTAURATION,
    AGRICULTURE,
    ENVIRONNEMENT_ET_DEVELOPPEMENT_DURABLE
}